### ISSUE TITLE
uv unwrapping

### ISSUE THREAD

**Issue by unicomp21** [bitbybit-dev/bitbybit#30]
Are there options for uv unwrapping within bitbybit?

**Comment by bitbybit-dev** [comment]
Hi, short answer - no, unwrapping is a bit off the scope for now as we primarily deal with BREP geometry and try to expose comfortable api on top of OpenCascade kernel. I would advise to look for some other library to do that.


 this algorithm seems to be quite involved and I'm not sure I'd even start writing that myself :) usually also requires some wasm compiled code.
